// Do not modify this file. It's generated by Framework.Cli.

namespace DatabaseIntegrate.dbo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using Framework.DataAccessLayer;
    using Framework.DataAccessLayer.Integrate;
    using Database.dbo;

    public static class HelloWorldIntegrateApplication
    {
        public enum IdNameEnum { [IdNameEnum(null)]None = 0 }

        public static HelloWorldIntegrate Row(this IdNameEnum value)
        {
            return RowList.Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdNameEnum IdName(string value)
        {
            return IdNameEnumAttribute.IdNameToEnum<IdNameEnum>(value);
        }

        public static string IdName(this IdNameEnum value)
        {
            return IdNameEnumAttribute.IdNameFromEnum(value);
        }

        public static List<HelloWorldIntegrate> RowList
        {
            get
            {
                var result = new List<HelloWorldIntegrate>
                {
                };
                return result;
            }
        }
    }
}
